; This file is for the FamiTone2 library and was generated by FamiStudio


.export _game_music_data = music_data_untitled


music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Dirtmouth
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $f0 ; 00 : Bleep
	.word @env0, @env1, @env1
	.byte $00
	.byte $70 ; 01 : LeadIntro
	.word @env2, @env1, @env1
	.byte $00
	.byte $70 ; 02 : LeadLo
	.word @env3, @env1, @env1
	.byte $00

@env0:
	.byte $c3,$5d,$c2,$32,$c1,$2b,$c0,$00,$06
@env1:
	.byte $c0,$7f,$00,$01
@env2:
	.byte $c6,$2f,$c5,$42,$c4,$27,$c3,$29,$c1,$24,$c0,$00,$0a
@env3:
	.byte $c8,$04,$c7,$06,$c6,$05,$c5,$06,$c4,$09,$c3,$08,$c2,$07,$c1,$24,$c0,$00,$10

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $82, $3e, $f9, $f9, $d9, $f9, $83, $3e, $d1, $40, $d1, $44, $a7, $3e, $f9, $f9, $85, $30, $d1, $34, $f9, $f9, $d9, $3e
	.byte $f9, $f9, $d9, $00, $f9, $81, $3e, $d1, $40, $d1, $44, $a7, $3a, $f9, $f9, $85, $40, $a7, $3e, $a7, $40, $f9, $f9, $85
	.byte $30, $d1
@song0ref54:
	.byte $56
@song0ref55:
	.byte $f9, $f9, $d9, $00, $f9, $ab, $56, $a7, $58, $d1, $5c, $a7, $56, $f9, $f9, $85, $48, $d1, $4c, $f9, $f9, $d9, $52, $f9
	.byte $f9, $d9, $56, $f9, $ab, $58, $d1, $5c, $d1, $60, $f9, $f9, $85, $62, $d1, $60, $f9, $ab, $58, $f9, $ab, $00, $f9, $f9
	.byte $d9, $f9, $f9, $db, $f9, $f9, $87, $60, $d1, $64, $f9, $ab, $6a, $d1, $5c, $d1, $6a
@song0ref120:
	.byte $f9, $f9, $d9, $56, $f9, $ab, $56, $a7, $58, $a7, $58, $a7, $5c, $a7, $56, $f9, $81, $4e, $a7, $4a, $a7, $4e, $f9, $81
	.byte $4a, $f9, $ab, $4e, $d1, $52, $d1, $52
	.byte $ff, $0f
	.word @song0ref55
	.byte $d9, $58, $f9, $f9, $85, $5c, $d1, $60, $f9, $f9, $d9, $00, $f9, $ab
@song0ref169:
	.byte $60, $a7, $62, $d1, $66, $a7, $60, $f9, $ab, $64, $f9, $ab, $66, $f9, $f9, $d9, $6a, $f9, $ab, $5c, $d1, $60, $a7, $62
	.byte $a7, $60, $f9, $f9, $d9, $5c, $f9, $d5, $60, $d1, $62, $a7, $5e, $f9, $f9, $d9, $52, $f9, $f9, $d9, $54, $a7, $58, $a7
	.byte $5c, $a7, $60, $a7, $6a, $a7, $6e, $a7, $70, $a7, $78, $a7, $02, $f9, $f9, $d9, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $84
@song0ref238:
	.byte $0a, $a7, $18
@song0ref241:
	.byte $a7, $22, $a7, $26, $a7, $28, $a7, $30, $a7, $28, $a7, $26, $a7
	.byte $ff, $10
	.word @song0ref238
	.byte $ff, $10
	.word @song0ref238
	.byte $ff, $10
	.word @song0ref238
	.byte $ff, $10
	.word @song0ref238
	.byte $06, $a7, $14
	.byte $ff, $0d
	.word @song0ref241
	.byte $02, $a7, $10, $a7, $22, $a7, $26, $a7, $28, $d1, $30, $d1, $02, $a7, $1a, $a7, $22, $a7, $28, $a7, $32, $a7, $22, $a7
	.byte $06, $d1
	.byte $ff, $10
	.word @song0ref238
	.byte $ff, $10
	.word @song0ref238
	.byte $ff, $10
	.word @song0ref238
	.byte $ff, $10
	.word @song0ref238
	.byte $02, $a7, $10, $a7, $1a, $a7, $1e, $a7, $22, $d1, $28, $d1, $1e, $a7, $26, $a7, $28, $a7, $30, $a7, $30, $d1, $26, $d1
	.byte $0c, $a7, $1a, $a7, $24, $a7, $2c, $a7, $32, $a7, $3c
@song0ref345:
	.byte $a7, $32, $a7, $2c, $a7, $10, $a7, $1e, $a7, $28, $a7, $30, $a7, $36, $d1, $30, $d1
	.byte $ff, $10
	.word @song0ref238
	.byte $ff, $10
	.word @song0ref238
	.byte $ff, $10
	.word @song0ref238
	.byte $ff, $10
	.word @song0ref238
	.byte $1a, $a7, $28, $a7, $36, $a7, $3a, $a7, $40, $a7, $36, $a7, $28, $a7, $1a, $a7, $18, $a7, $26, $a7, $30, $a7, $34, $a7
	.byte $36, $a7, $34, $a7, $30, $a7, $26, $a7, $10, $a7, $1e, $a7, $28, $a7, $30, $a7, $36, $a7, $28, $a7, $1e, $d1, $14, $a7
	.byte $22, $a7, $2c, $a7, $36, $a7, $34, $a7, $2c, $a7, $22, $a7, $14, $a7, $0a, $a7, $10, $a7, $18, $a7, $22, $a7
@song0ref444:
	.byte $26, $a7, $22, $a7, $18, $a7, $10, $a7, $02, $a7, $10, $a7, $1a, $a7, $22, $a7, $26, $a7, $22, $a7, $10, $d1, $02, $d1
	.byte $1a, $a7, $22, $a7, $26, $a7, $22, $a7, $1a, $a7, $22
@song0ref479:
	.byte $a7, $02, $a7, $10, $a7, $18, $a7, $22, $a7, $28, $a7, $22, $a7, $0c, $a7, $1e, $a7, $0a, $a7, $18, $a7, $22, $d1
	.byte $ff, $10
	.word @song0ref444
	.byte $28, $a7, $22, $a7, $1a, $a7, $10, $a7, $02, $a7, $14, $a7, $1c, $a7, $22, $a7, $24, $a7, $22, $a7, $1c, $a7, $14
	.byte $ff, $0d
	.word @song0ref479
	.byte $18, $a7, $22, $a7, $0c, $a7, $1a, $a7, $24, $a7, $2c, $a7, $32, $a7, $3a
	.byte $ff, $0d
	.word @song0ref345
	.byte $3a, $f9, $ab, $14, $a7, $24, $a7, $2c, $a7, $32, $a7, $00, $a7, $32, $a7, $2c, $a7, $24, $a7, $16, $a7, $0c, $a7, $18
	.byte $a7, $1e, $a7, $24, $a7, $2e, $a7, $24, $a7, $1e, $a7, $02, $a7, $10, $a7, $1a, $a7, $22, $a7, $28, $d1, $22, $d1, $0a
	.byte $a7, $18, $a7, $22, $a7, $26, $a7, $28, $a7, $30, $a7, $3a, $a7, $40, $a7, $48, $f9, $f9, $d9, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
@song0ref620:
	.byte $f9, $f9, $db, $f9, $f9, $db, $f9, $f9, $db, $f9, $f9, $db, $f9, $f9, $db, $f9, $f9, $db, $f9, $f9, $db, $f9, $f9, $db
	.byte $80
	.byte $ff, $37
	.word @song0ref54
	.byte $db, $f9, $f9, $db, $52
	.byte $ff, $20
	.word @song0ref120
	.byte $f9, $f9, $d9, $f9, $ad, $56, $a7, $58, $d1, $5c, $a7, $56, $f9, $f9, $d9, $58, $f9, $f9, $85, $5c, $d1, $60, $f9, $f9
	.byte $d9, $f9, $ad
	.byte $ff, $13
	.word @song0ref169
	.byte $00, $f9, $ab
	.byte $ff, $12
	.word @song0ref620
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $18
	.word @song0ref620
	.byte $ff, $18
	.word @song0ref620
	.byte $ff, $18
	.word @song0ref620
	.byte $ff, $18
	.word @song0ref620
	.byte $ff, $15
	.word @song0ref620
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $18
	.word @song0ref620
	.byte $ff, $18
	.word @song0ref620
	.byte $ff, $18
	.word @song0ref620
	.byte $ff, $18
	.word @song0ref620
	.byte $ff, $15
	.word @song0ref620
	.byte $fd
	.word @song0ch4loop
