; This file is for the FamiTone2 library and was generated by FamiStudio


.export _menu_music_data = music_data_hollow_knight_theme


music_data_hollow_knight_theme:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Hollow Knight
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_hollow_knight_theme
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $f0 ; 00 : LeadIntro
	.word @env1, @env2, @env2
	.byte $00
	.byte $30 ; 01 : LeadLo
	.word @env3, @env2, @env2
	.byte $00
	.byte $30 ; 02 : Meu Instrumento
	.word @env0, @env2, @env2
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c1,$c2,$c3,$c4,$c5,$c6,$c7,$c7,$c8,$c8,$c7,$00,$0a
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $cc,$04,$cb,$04,$ca,$04,$c9,$03,$c8,$04,$c7,$03,$c6,$08,$c5,$06,$c4,$05,$c3,$03,$c2,$00,$14

@samples:

@song0ch0:
	.byte $fb, $01, $82, $62, $ef, $62, $f3, $66, $b7, $68, $bb, $66, $f9, $f9, $e9, $62, $b5, $58, $b7, $5a, $f3, $58, $b7, $54
	.byte $bb, $58, $f9, $f9, $e9, $62, $ef, $62, $f3, $66, $b7, $68, $bb, $6c, $f9, $f9, $e9, $70, $b5, $68, $b7, $66, $bb, $62
	.byte $b5, $5e, $f5, $62, $f9, $f9, $e9, $00, $f9, $f9, $e9
@song0ref60:
	.byte $4a, $ef, $4a, $f3, $4e, $b7, $50, $bb, $4e, $f9, $f9, $e9, $4a, $b5, $40, $b7, $42, $f3, $40, $b7, $3c, $bb, $40, $f9
	.byte $f9, $e9, $4a, $ef, $4a, $f3, $4e, $b7, $50, $bb, $54, $f9, $f9, $e9, $58, $97, $5a, $9b, $58, $f5, $50, $ef, $46, $bb
	.byte $4a, $ef, $46, $f9, $b3, $3c, $bb, $40, $f9, $eb, $32, $f5, $f9, $f9, $eb, $d7, $40, $f9, $f9, $91, $f9, $ed, $48, $f5
	.byte $48, $f9, $f9, $e9, $4a, $f9, $f9, $ab, $4e, $9b, $50, $9d, $54, $f9, $f9, $e9, $58, $f9, $b3, $5e, $f9, $b3, $62, $f9
	.byte $f9, $e9
@song0ch0loop:
	.byte $00, $fd
	.word @song0ch0loop
@song0ch1:
	.byte $80, $32, $b5, $40, $b7, $42, $f9, $f1, $32, $b5, $3c, $b7, $40, $f9, $f1, $32, $b5, $38, $b7, $3c, $f9, $f1, $32, $b5
	.byte $36, $b7, $38, $bb, $36, $b5, $2e, $f5, $32, $b5, $40, $b7, $42, $f9, $f1, $2e, $b5, $40, $b7, $3c, $f9, $f1, $2a, $b5
	.byte $38, $b7, $3c, $f9, $f1, $24, $b5, $2e, $b7, $32, $bb, $3c, $b5, $32, $b7, $2e, $bb, $3c, $f9, $eb, $20, $f5, $1a, $b5
	.byte $28, $b7, $2a, $f9, $f1, $1a, $b5, $24, $b7, $28, $f9, $f1, $1a, $b5, $20, $b7, $24, $f9, $f1, $16, $b5, $20, $b7, $1e
	.byte $f3, $16, $f5, $12, $b5, $20, $b7, $24, $f9, $f1, $0c, $b5, $1a, $b7, $24, $bb, $28, $b5, $2a, $b7, $32, $bb, $08, $b5
	.byte $1a, $b7, $20, $bb, $28, $b5, $32, $b7, $22, $bb, $14, $b5, $22, $b7, $18, $bb, $24, $b5
@song0ref301:
	.byte $1e, $f5, $1a, $b5, $28, $b7, $2a, $bb, $28, $b5, $2a, $b7, $28, $bb, $1a, $b5, $24, $b7, $28, $bb, $24, $b5, $28, $b7
	.byte $24, $bb, $1a, $b5, $20, $b7, $24, $bb, $20, $b5, $24, $b7, $20, $bb, $1e, $ef, $18, $f3
	.byte $ff, $26
	.word @song0ref301
	.byte $16, $b5, $1e, $b7, $24, $bb, $2e, $b5, $36, $f5, $36, $f9, $f9, $e9
@song0ch1loop:
	.byte $00, $fd
	.word @song0ch1loop
@song0ch2:
@song0ref365:
	.byte $f9, $f9, $eb, $f9, $f9, $eb, $f9, $f9, $eb, $f9, $f9, $eb, $f9, $f9, $eb, $f9, $f9, $eb, $f9, $f9, $eb, $f9, $f9, $eb
	.byte $f9, $f9, $eb, $84
	.byte $ff, $26
	.word @song0ref60
	.byte $00, $f9, $f9, $e9
	.byte $ff, $1b
	.word @song0ref365
	.byte $f9, $f9, $eb
@song0ch2loop:
	.byte $00, $fd
	.word @song0ch2loop
@song0ch3:
	.byte $ff, $1b
	.word @song0ref365
	.byte $ff, $1b
	.word @song0ref365
	.byte $ff, $18
	.word @song0ref365
@song0ch3loop:
	.byte $00, $fd
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $1b
	.word @song0ref365
	.byte $ff, $1b
	.word @song0ref365
	.byte $ff, $18
	.word @song0ref365
@song0ch4loop:
	.byte $00, $fd
	.word @song0ch4loop
