; This file is for the FamiTone2 library and was generated by FamiStudio


.export _hornet_music_data = music_data_untitled_2


music_data_untitled_2:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Hornet
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_untitled_2
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $70 ; 00 : LeadIntro
	.word @env0, @env3, @env3
	.byte $00
	.byte $70 ; 01 : LeadLo
	.word @env2, @env3, @env3
	.byte $00
	.byte $30 ; 02 : Meu Instrumento
	.word @env1, @env3, @env3
	.byte $00

@env0:
	.byte $c6,$02,$c5,$05,$c4,$07,$c3,$11,$c2,$14,$c1,$1f,$c0,$00,$0c
@env1:
	.byte $cf,$7f,$00,$00
@env2:
	.byte $c6,$04,$c5,$06,$c4,$05,$c3,$07,$c2,$0a,$c1,$06,$c0,$00,$0c
@env3:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $80, $5c
@song0ref6:
	.byte $9b, $3a, $9b, $3a, $9b, $3a, $9b, $3a, $9b, $3a, $9b, $40, $9b, $3c, $9b, $36, $9b, $3a, $9b, $32, $9b, $30
	.byte $ff, $0b
	.word @song0ref6
	.byte $3a, $9b, $36, $9b, $32, $9b, $2c, $9b, $32, $9b, $30, $b9, $3a
	.byte $ff, $16
	.word @song0ref6
	.byte $9b, $3a, $9b, $3a, $9b, $3a, $9b, $3c, $9b, $3c, $9b, $3c, $9b, $40, $9b, $40, $9b, $40
@song0ref65:
	.byte $9b, $44, $9b, $44, $9b, $44, $9b, $48, $9b, $48, $9b, $48, $9b, $4a, $9b, $4a, $9b, $4a
@song0ref83:
	.byte $9b, $4e, $9b, $4a, $9b, $48, $9b, $4a, $9b, $48, $9b, $44
	.byte $ff, $0c
	.word @song0ref83
	.byte $9b, $58, $9b, $54, $9b, $52, $9b, $54, $9b, $52, $9b, $4e, $9b, $4e, $9b, $4a, $9b, $48, $9b, $48, $8d, $44, $8b, $40
	.byte $8d, $3c, $8b, $3a, $8d, $36, $8b, $44, $d7, $52, $d7, $52, $f9, $b7, $58, $b9, $54, $b9, $4e, $b9, $52, $b9, $4a, $b9
	.byte $48, $b9, $44, $d7, $4e, $d7, $4a, $d7, $48, $d7, $3c, $8d, $40, $8b, $44, $8d, $48, $8b, $40, $8d, $44, $8b, $48, $8d
	.byte $4a, $8b, $44, $8d, $48, $8b, $4a, $8d, $4e, $8b, $48, $8d, $4a, $8b, $4e, $8d, $52, $8b, $4a, $8d, $4e, $8b, $52, $8d
	.byte $54, $8b, $4e, $8d, $52, $8b, $54, $8d, $58
@song0ref203:
	.byte $8b, $5c, $8d, $52, $8b, $54, $8d, $5a, $8b, $5c, $8d, $52, $8b, $54, $8d, $5a
	.byte $ff, $10
	.word @song0ref203
	.byte $ff, $10
	.word @song0ref203
	.byte $8b, $5c, $8d, $54, $8b, $5a, $8d, $5c, $8b, $60, $8d, $5a, $8b, $5c, $8d, $60, $8b, $62, $8d, $5c, $8b, $60, $8d, $62
	.byte $8b, $66, $8d, $60, $8b, $62, $8d, $66, $8b, $6a, $8d, $66, $8b, $6a, $8d, $6c, $8b, $70, $8d, $6a, $8b, $6c, $8d, $70
	.byte $8b, $74, $d7, $4e, $d7, $4a, $d7, $48
@song0ref281:
	.byte $d7
@song0ref282:
	.byte $5c, $9b, $5c, $9b, $44, $9b, $5c, $9b, $44, $9b, $44, $9b
	.byte $ff, $0c
	.word @song0ref282
	.byte $5c, $d7, $66, $d7, $62, $d7, $60
	.byte $ff, $0d
	.word @song0ref281
	.byte $ff, $0c
	.word @song0ref282
	.byte $44, $d7, $4e, $d7, $4a, $d7, $48, $d7, $30, $d7, $3a, $d7, $36, $d7, $30, $d7, $4c, $d7, $56, $d7, $52, $d7, $50, $d7
	.byte $52, $9b, $44, $9b, $44
	.byte $ff, $13
	.word @song0ref65
	.byte $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $82, $0c
@song0ref348:
	.byte $9b
@song0ref349:
	.byte $2c, $9b, $2c, $9b, $2c, $9b, $2c, $9b, $2c, $9b, $2c
	.byte $ff, $0c
	.word @song0ref348
	.byte $ff, $0b
	.word @song0ref348
	.byte $24, $9b, $24, $9b, $24, $9b, $24, $d7
	.byte $ff, $0b
	.word @song0ref349
	.byte $ff, $0c
	.word @song0ref348
	.byte $ff, $0c
	.word @song0ref348
	.byte $9b, $30, $9b, $30, $9b, $30, $9b, $30, $9b, $30, $9b, $30
	.byte $ff, $0c
	.word @song0ref348
	.byte $ff, $0c
	.word @song0ref348
	.byte $ff, $0c
	.word @song0ref348
	.byte $9b, $24, $9b, $24, $9b, $24, $9b, $24, $9b, $24, $9b, $24, $9b, $16, $f9, $b7, $2c
	.byte $ff, $15
	.word @song0ref6
	.byte $2c
	.byte $ff, $0b
	.word @song0ref6
	.byte $3a
	.byte $ff, $0b
	.word @song0ref6
	.byte $3a, $9b, $32, $9b, $32, $9b, $32, $9b, $32, $9b, $32, $9b, $32, $9b, $3a, $9b, $36, $9b, $30, $9b, $32, $9b, $2c, $9b
	.byte $30
	.byte $ff, $0c
	.word @song0ref348
	.byte $9b, $30, $9b, $30, $9b, $30, $9b, $32, $9b, $30, $9b, $30, $9b, $2c, $d7, $3a, $d7, $3a, $b9, $22, $b9, $1a, $b9, $28
	.byte $ab, $24, $a9, $18, $9b, $1e, $9b, $18, $9b, $22, $9b, $18, $9b, $1e, $9b, $22, $9b, $24, $9b, $28, $9b, $24, $9b, $14
	.byte $9b, $14, $9b, $1e, $9b, $14, $9b, $14, $9b, $1a, $9b, $10, $9b, $10, $9b, $18, $9b, $10, $9b, $10
@song0ref528:
	.byte $9b, $0a, $9b, $0a, $9b, $0a, $9b, $0a, $9b, $0a, $9b, $0a, $9b
@song0ref541:
	.byte $08, $9b, $08, $9b, $08, $9b, $08, $9b, $08, $9b, $08, $9b, $1e, $9b, $1e, $9b, $1e, $9b, $1e, $9b, $1e, $9b, $1e, $9b
	.byte $18, $9b, $18, $9b, $18, $9b, $1a, $9b, $1a, $9b, $1a
	.byte $ff, $19
	.word @song0ref528
	.byte $26, $9b, $1e, $9b, $1e, $9b, $28, $9b, $1e, $9b, $1e, $9b, $24, $9b, $18, $9b, $18, $9b, $24, $9b, $1a, $9b, $1a, $9b
	.byte $2a, $9b, $12, $9b, $12, $9b, $2a, $9b, $12, $9b, $12, $9b, $28, $9b, $10, $9b, $10, $9b, $28, $9b, $10, $9b, $10, $9b
	.byte $2e, $9b, $16, $9b, $16, $9b, $2e, $9b, $16, $9b, $16, $9b, $2c, $9b, $14, $9b, $14, $9b, $2c, $9b, $14, $9b, $14, $9b
	.byte $0c, $9b, $0c, $9b, $0c, $b9
@song0ref657:
	.byte $0c, $9b, $0c, $9b, $0c, $9b, $0c, $9b, $0c, $9b, $0c, $9b, $0c, $9b, $0c, $9b, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
@song0ref677:
	.byte $f9, $b9, $f9, $b9, $f9, $b9, $f9, $b9, $f9, $b9, $f9, $b9, $f9, $b9, $84
@song0ref692:
	.byte $10, $9b, $10, $9b, $10, $9b, $10, $9b, $10, $9b, $10, $9b
	.byte $ff, $0c
	.word @song0ref692
	.byte $ff, $0c
	.word @song0ref541
@song0ref710:
	.byte $06
@song0ref711:
	.byte $9b, $06, $9b, $06, $9b, $06, $9b, $06, $9b, $06, $9b
	.byte $ff, $0c
	.word @song0ref710
	.byte $02, $f9, $b7, $0c
@song0ref729:
	.byte $9b, $14, $9b, $14, $9b, $14, $9b, $14, $9b, $14, $9b, $14
	.byte $ff, $0c
	.word @song0ref729
	.byte $ff, $0c
	.word @song0ref729
	.byte $ff, $0b
	.word @song0ref729
	.byte $ff, $10
	.word @song0ref657
	.byte $0c, $9b, $0c, $9b, $0c, $9b, $0c
	.byte $ff, $0b
	.word @song0ref711
	.byte $06
	.byte $ff, $0d
	.word @song0ref528
@song0ref767:
	.byte $00, $f9, $b7, $f9, $b9, $f9, $b9, $f9, $b9, $f9, $b9, $f9, $b9
@song0ref780:
	.byte $22, $9b, $22, $9b, $00, $9b, $22, $9b, $00, $b9, $20, $9b, $20, $9b, $00, $9b, $20, $9b, $00, $b9, $0e, $9b, $0e, $9b
	.byte $0e, $9b, $0e, $9b, $0e, $9b, $0e
	.byte $ff, $0d
	.word @song0ref528
	.byte $ff, $1f
	.word @song0ref780
	.byte $ff, $0d
	.word @song0ref528
	.byte $ff, $0d
	.word @song0ref767
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $0e
	.word @song0ref677
	.byte $ff, $0e
	.word @song0ref677
	.byte $ff, $0e
	.word @song0ref677
	.byte $ff, $0e
	.word @song0ref677
	.byte $ff, $0e
	.word @song0ref677
	.byte $ff, $0c
	.word @song0ref677
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $0e
	.word @song0ref677
	.byte $ff, $0e
	.word @song0ref677
	.byte $ff, $0e
	.word @song0ref677
	.byte $ff, $0e
	.word @song0ref677
	.byte $ff, $0e
	.word @song0ref677
	.byte $ff, $0c
	.word @song0ref677
	.byte $fd
	.word @song0ch4loop
